# -*- coding: utf-8 -*-
"""firstnotebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLk0k4RiRD1ahmeLH9c2tWZDKk1RBenj
"""

print("Hello World")

name='manoshree from INDIA'
Address='TamilNadu'
print(name.index('f'))
print(name.capitalize())
print(name.count('a'))
print(name.lower())
print(name.center(5))

lst=[1,2,3,4,5,6,7,8,[9,10,11],12,[13,14]]
lst.append('last')
print(lst)
print(lst.count(2))
lst.pop()
print(lst)
lst.insert(0,0)
print(lst)
print(lst.reverse())
print(lst)

d={"namee": "Manoshree", "Address": "INDIA","Gender" : "Female", "Courses":{ "Maincourse":" Python","Additional":"JAVA"}}
print(d["namee"])
print(d.keys())
print(d.values())
print(d.get("Courses").get("Maincourse"))
d.update({"Year":3})
print(d)









